---
- name: List configured runners as json
  win_command: "{{ gitlab_runner_executable }} --log-format json list"
  args:
    chdir: "{{ gitlab_runner_config_file_location }}"
  register: registered_runners_json_result
  changed_when: false
  check_mode: false

- name: Initialze runner list
  set_fact:
    registered_gitlab_runner_names: []

- name: Create list of configured runners
  set_fact:
    registered_gitlab_runner_names: "{{ registered_gitlab_runner_names + [json_item['msg']] }}"
  vars:
    json_item: "{{ item | from_json }}"
  loop: "{{ registered_runners_json_result.stderr_lines }}"
  when: "'Executor' in json_item"

- name: Print registered runners
  debug: var=registered_gitlab_runner_names
