---
- name: Converge (apply role with selected vars)
  hosts: runner
  become: true

  vars_files:
    - vars/common.yml
    - vars/initial.yml

  pre_tasks:
    - name: Wait for mock GitLab API
      ansible.builtin.wait_for:
        host: mock
        port: 8000
        delay: 2
        timeout: 120

  roles:
    - role: riemers.gitlab_runner
