---
- name: Converge (apply role with selected vars)
  hosts: runner
  become: true

  vars_files:
    - ../default/vars/common.yml
    - ../default/vars/updated.yml

  roles:
    - role: riemers.gitlab_runner
