---
driver:
  name: docker
  docker_networks:
    - name: testnet
      ipam_config:
        - subnet: "172.28.0.0/16"
      dns:
        - 127.0.0.11

platforms:
  - name: mock
    image: riemers-gitlab-runner-mock
    pre_build_image: true
    override_command: false
    networks:
      - name: testnet

  - name: runner
    image: geerlingguy/docker-ubuntu2204-ansible
    pre_build_image: true
    networks:
      - name: testnet
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /run/lock
    command: /sbin/init

provisioner:
  name: ansible
  env:
    EXPECTED_TOML: ../default/expected/updated.toml
  inventory:
    hosts:
      all:
        hosts:
          mock:
          runner:

verifier:
  name: testinfra
  options:
    v: true

scenario:
  test_sequence:
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - verify
    - destroy
